### ISSUE TITLE
Docker: Как программно поймать входящий звонок (обходное решение)

### ISSUE THREAD

**Issue by twocolors** [Moleus/domru#12]
Идея и оригинал взят https://github.com/alexmorbo/domru/issues/43

**!!! Пути везде ставим свои, знание работы с docker приветствуется !!!**

Мой кейс было все это завернуть в docker и стандартный AVD
Ставим чистый docker без sdk и AVD , нам надо смонтировать свой SDK и AVD microG
```
sudo docker run -it -e MEMORY=2048 -e CORES=2 -e DISABLE_ANIMATION=true -e DISABLE_HIDDEN_POLICY=true -e SKIP_AUTH=true --rm --device /dev/kvm -p 5555:5555 --entrypoint /bin/bash -v /home/dietpi/.android/sdk:/opt/android -v /home/dietpi/.android/data:/data halimqarroum/docker-android:minimal
```
В контейнере добавляем репозиторий microG
```
root@android:/opt# cat /root/.android/repositories.cfg
count=1
disp00=microG System Images
src00=https://microg.org/sdk/sys-img.xml
enabled00=true
root@android:/opt#
```
Ставим microG AVD
```
export ABI=microg/x86_64
export INSTALL_ANDROID_SDK=1
export CMD_LINE_VERSION=9477386_latest
export ANDROID_PLATFORM_VERSION="platforms;android-29"
export PACKAGE_PATH="system-images;android-29;microg;x86_64"
root@android:/opt# ./install-sdk.sh
```
Все, теперь можно запускать контейнер с своим AVD и SDK, у меня это вот так
```
  android:
    container_name: "android"
    hostname: "android"
    image: "halimqarroum/docker-android:minimal"
    environment:
      - TZ=Europe/Moscow
      - MEMORY=2048
      - CORES=2
      - DISABLE_ANIMATION=true
      - DISABLE_HIDDEN_POLICY=true
      - SKIP_AUTH=true
      - ABI=microg/x86_64
      - ANDROID_PLATFORM_VERSION=platforms;android-29
      - PACKAGE_PATH=system-images;android-29;microg;x86_64
    volumes:
      - "/home/dietpi/.android/data:/data"
      - "/home/dietpi/.android/sdk:/opt/android"
    devices:
      - "/dev/kvm:/dev/kvm"
    restart: unless-stopped
    networks:
      - stalker
    ports:
      - 5555:5555
#    deploy:
#      resources:
#        limits:
#          cpus: '0.25'
#          memory: 2G
```
Подключаемся к контейнеру по средствам scrcpy (ключ берем приватный вот тут https://github.com/HQarroum/docker-android/blob/main/keys/adbkey)

Какие приложение надо поставить, что бы работало:
**1. F-Droid , подключаем репу https://microg.org/download.html ставим microg service**
![image](https://github.com/moleus/domru/assets/207796/e89a7f93-89db-494c-a745-219232637fd4)
**2. В microg , разрешаем все через FSM**
![image](https://github.com/moleus/domru/assets/207796/d0cbecf5-f073-4416-9323-057e77bfd2f2) 
![image](https://github.com/moleus/domru/assets/207796/683b3d14-579e-4c6d-ab0f-60aecda297f9)
**3. Далее ставим Умный дом.ру и что бы ловить события я выбрал MacroDroid, MacroDroid разрешаем читать LOGCAT**
```
adb shell pm grant com.arlosoft.macrodroid android.permission.WRITE_SECURE_SETTINGS
adb shell pm grant com.arlosoft.macrodroid android.permission.CHANGE_CONFIGURATION
adb shell pm grant com.arlosoft.macrodroid android.permission.DUMP
adb shell pm grant com.arlosoft.macrodroid android.permission.SET_VOLUME_KEY_LONG_PRESS_LISTENER
adb shell pm grant com.arlosoft.macrodroid android.permission.READ_LOGS
```
**4. Настраиваем Умный дом.ру через  FSM и дальше делаем MacroDroid что бы ловить вхд. звонок**
![image](https://github.com/moleus/domru/assets/207796/23878fce-e68e-42cb-b384-d6a139ce39cd)
![image](https://github.com/moleus/domru/assets/207796/0593f66c-1d79-481b-9759-9742608acadb)

Текст макроса
```
GmsGcmMcsInput
com.ertelecom.smarthome*CALL_INCOMING
```

### Все, приложение Умный дом.ру и MacroDroid , не закрывать !!! ...
